// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztxgmqunqsookgpmluyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0eGdtcXVucXNvb2tncG1sdXlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTAzODQsImV4cCI6MjA3Mjg4NjM4NH0.DK2oySyoBu29Z-uNsrmhX9VtuADqtjwg2OxBj1jXYas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'masomo-hub-connect',
    },
  },
  db: {
    schema: 'public',
  },
      realtime: {
        params: {
          eventsPerSecond: 5,
        },
      },
});